### ISSUE TITLE
ChipGroupLayout will crash if click on already selected chip

### ISSUE THREAD

**Issue by aSvetenco** [maximbircu/devtools-library#43]
## Abstract
 ChipGroupLayout will crash if click on already selected chip

**Platform related info:** 
 - OS:  Android 
 - OS version:  Android 10(29) 

## Steps to reproduce
1. Go to 'whatever screen where enum tools are available "MEMORY" for example'
2. Click on 'second-option'
3. Then click one more time on 'second-option'
4. App will force-stop 

**Expected**
The second option will remain selected 

**Actual**
 App force-stop 

## Additional context
 Crash occurs because of 'getCheckedChipId' returns 'NO_ID (-1)'. ChipGruops returns NO_ID in order to unselect already selected chip. I dont know if this behavior applicable for devtools-library. If yes, can be added a check for NO_ID before retrieving chipName from chips map.

**Comment by maximbircu** [comment]
Thanks @aSvetenco, I notice this issue too yesterday. I'll fix it in https://github.com/maximbircu/devtools-library/pull/42 👍
