### ISSUE TITLE
Contributing link from quick start is invalid

### ISSUE THREAD

**Issue by blainepwnz** [maximbircu/devtools-library#55]
Clicking on **contributing guidelines** on [this page](https://github.com/maximbircu/devtools-library/blob/master/documentation/quickstart/quick-start.md) leads to 404

**Comment by mbircu-ellation** [comment]
Thanks @blainepwnz I'll update this and will check other links too 👍

**Comment by maximbircu** [comment]
Thanks @blainepwnz I'll update this and will check other links too 👍
